version: '2.1'

networks:
  selenoid:
    external: False
    name: selenoid

services:

  tests:
    build: config_tests
    tty: true
    networks:
      - selenoid
    volumes:
          - "${WORKSPACE}/tests_project:/src"
          - "${WORKSPACE}/alluredir:/tmp/allure"
          - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /src
    entrypoint: /bin/bash /src/start_tests.sh
    environment:
      - PATH_TESTS= #При необходимости запустить какой нибудь отдельный вид тестов
      - THREADS=4
    depends_on:
      myapp:
        condition: service_healthy

  myapp:
    image: "myapp"
    networks:
      - selenoid
    volumes:
      - "${WORKSPACE}/final_project/myapp_config/app_config.txt:/app/config/app_config.txt"
    command: /app/myapp --config=/app/config/app_config.txt
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "127.0.0.1:8083" ]
      timeout: 10s
      retries: 15

  myapp_proxy:
    image: "nginx:stable"
    networks:
      - selenoid
    volumes:
      - "${WORKSPACE}/final_project/myapp_config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      myapp:
        condition: service_started

  db:
    image: "mysql:latest"
    networks:
      - selenoid
    volumes:
      - "${WORKSPACE}/final_project/myapp_config/database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
    environment:
      MYSQL_DATABASE: vkeducation
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: test_qa
      MYSQL_PASSWORD: qa_test
    command: mysqld --innodb-buffer-pool-size=0M
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ptoor", "ping", "-h", "db" ]
      timeout: 5s
      retries: 15

  phpmyadmin:
    image: "phpmyadmin:latest"
    networks:
      - selenoid
    ports:
      - "8086:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=toor
    depends_on:
      - db

  vk_api:
    build: tests_project/mock
    networks:
      - selenoid
    ports:
      - "8085:8085"

  selenoid_chrome:
    image: "selenoid/chrome:99.0"
    depends_on:
      - selenoid

  selenoid:
    image: "aerokube/selenoid:latest"
    networks:
      - selenoid
    ports:
      - "4444:4444"
    volumes:
      - "${WORKSPACE}/final_project/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [ "-conf", "/etc/selenoid/browsers.json",  "-container-network", "selenoid", "-timeout", "5m" ]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    networks:
      - selenoid
    ports:
      - "8888:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      - selenoid
